# loggger_name
# logger_level
# logger_file

logger:
  name: python25
  level: WARNING
  file: python25.txt

excel:
  file: test_cases.xlsx
  sheet: Register


#database:
#  host: "120.78.128.25"
#  port: 3306
#  user: "future"
#  password: '123456'
#  charset: 'utf8'
#  database: 'futureloan'
#  cursorclass: 'DictCursor'


#user:
#  mobile_phone: '13712341234'
#  pwd: '12345678'

database:
  host: "mysql-test.klxuexi.net"
  port: 3306
  user: "root"
  password: '123456'
  charset: 'utf8'
  database: 'edu-crm'
  cursorclass: 'DictCursor'


  1





